core:
  # log format
  log_format: '[%(levelname)s] %(asctime)s - %(name)s/%(filename)s/%(funcName)s, %(lineno)s: %(message)s'

  # 모의투자 계좌('-' 없이)
  test_account: ''

  # 모의투자 비밀번호
  test_password: ''

  # 실제 계좌명('-' 없이)
  real_account: ''

  # 실제 계좌 비밀번호
  real_password: ''


database:
  # sqlite일 경우 절대경로로 설정 가능
  sqlalchemy_conn_str: 'sqlite:///database.db'
