user:
  # 모의투자시 사용하는 계정
  test_account: ''
  test_password: ''

  # 실제 계정
  real_account: ''
  real_password: ''

# backend로 사용할 database
database:
  sqlalchemy_conn_str: 'sqlite:///database.db'


rebalance:

  # 계좌 전체 금액 중 사용할 금액 %
  limit: 80%

  # limit 중 국내 주식 비율
  domestic_percent: 19%

  # limit 중 외국 주식 비율
  overseas_percent: 30%